# Generated by Django 3.2.2 on 2021-09-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('labels', '0001_initial'),
        ('tasks', '0002_auto_20210909_1716'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Label',
        # ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author', to='users.taskuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='executor', to='users.taskuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='labels.Label'),
        ),
    ]
