# Generated by Django 3.2.2 on 2021-09-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210909_1910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
