# Generated by Django 3.2.2 on 2021-07-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210718_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
